# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: EMPIRE
description: "Sonic Multiplicities"
keywords: 'music,electroacoustic,experimental,classical,violin,computer,AI,supercollider'
author:
  name:
  job_title:
  location: Brooklyn, NY
  email: andrew@grathwohl.me
  social_links:
    - name: bandcamp
      url: https://empire-sm.bandcamp.com/
    - name: github
      url:
    - name: instagram
      url:
    - name: linkedin
      url:
    - name: soundcloud
      url: https://soundcloud.com/empire-sm
    - name: stackoverflow
      url:
    - name: twitter
      url: https://twitter.com/EmpireSM_
home:
  section1: <h1>EMPIRE</h1>
  section2: <h3></h3>
  section3: <h2>Sonic Multiplicities</h2>
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License. 
  footer_content: EMPIRE represents the most extreme effort ever made towards empowering the solo instrumentalist with software.

disqus:
  shortname: # e.g. yizeng
  public_key: # e.g. ULZ0b9TFefCUJHKQd4JCKv2v3u27YoG7YG8zXPewkWrT333Z0Se9YnxLzoV6VM8W
google_analytics: # e.g. 'UA-42456515-5'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5 

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
